name: Node.js CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  schedule:
    - cron: '0 0 * * 1'  # Tous les lundis à minuit

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16, 18, 20]
        exclude:
          - os: ubuntu-latest
            node-version: 16
          - os: windows-latest
            node-version: 18
          - os: macos-latest
            node-version: 20
        include:
          - os: windows-latest
            node-version: 22
      max-parallel: 2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.os }}-node-${{ matrix.node-version }}
          path: dist/

  conditional-job:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: build-ubuntu-latest-node-18
          path: ./artifact

      - name: Simulate deployment
        run: echo "Deploying artifact for Ubuntu with Node 18"
